### PR TITLE
Testing Stg Command Bot on Polkadot

### PR DESCRIPTION
**Pull request by mordamax**

### CODE REVIEW

**Comment by alvicsam** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=as-test-new-runner -c bench $ polkadot

**Comment by mordamax** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=as-test-new-runner -c bench $ polkadot

**Comment by mordamax** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=as-test-new-runner -c bench $ polkadot

**Comment by mordamax** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=as-test-new-runner -c bench $ polkadot

**Comment by mordamax** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=as-test-new-runner -c bench-bot $ runtime polkadot-dev pallet_fast_unstake

**Comment by mordamax** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=as-test-new-runner -c bench $ runtime polkadot-dev pallet_fast_unstake

**Comment by alvicsam** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=as-test-new-runner -c bench $ polkadot

**Comment by alvicsam** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=as-test-new-runner -c bench $ runtime polkadot-dev pallet_fast_unstake

**Comment by alvicsam** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=as-test-new-runner -c bench $ runtime polkadot-dev pallet_fast_unstake

**Comment by alvicsam** [comment]
- Hey doc, everybody ignores me
- Next!

**Comment by mordamax** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=as-test-new-runner -c bench $ runtime polkadot-dev pallet_fast_unstake

**Comment by mordamax** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=mak/update-try-tuntime-command -c try-runtime $ kusama

**Comment by mordamax** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=mak/update-try-tuntime-command -c try-runtime $ kusama

**Comment by mordamax** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=mak/update-try-tuntime-command -c try-runtime $ kusama

**Comment by mordamax** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=mak/update-try-tuntime-command -c try-runtime $ kusama

**Comment by alvicsam** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=mak/update-try-tuntime-command -c try-runtime $ kusama

**Comment by alvicsam** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=as-test-new-runner -c bench $ runtime polkadot-dev pallet_fast_unstake

**Comment by alvicsam** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=as-test-new-runner -c bench $ runtime polkadot-dev pallet_fast_unstake

**Comment by alvicsam** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=as-test-new-runner -c bench $ runtime polkadot-dev pallet_fast_unstake

**Comment by alvicsam** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=as-test-new-runner -c bench $ runtime polkadot-dev pallet_fast_unstake

**Comment by mordamax** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=mak/update-try-tuntime-command -c try-runtime $ kusama

**Comment by alvicsam** [comment]
/cmd queue -v PIPELINE_SCRIPTS_REF=as-test-new-runner -c bench $ runtime polkadot-dev pallet_fast_unstake

**Comment by mordamax** [comment]
> User @mordamax, please sign the CLA [here](http://cla.parity-stg.parity.io/sign_cla/1177472/3).

@alvicsam someone just installed CLA on stg? :)

**Comment by alvicsam** [comment]
yep :)

**Comment by alvicsam** [comment]
/cmd queue -c sample $ echo test

**Comment by mordamax** [comment]
bot help

**Comment by mordamax** [comment]
bot help

**Comment by mordamax** [comment]
bot help -v PIPELINE_SCRIPTS_REF=mak/bench-all

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all

**Comment by mordamax** [comment]
bot bench -v PIPELINE_SCRIPTS_REF=mak/bench-all $ all kusama

**Comment by mordamax** [comment]
bot cancel 3-7486fd2a-d48d-4756-904e-59d7ed654a71

**Comment by mordamax** [comment]
closing as tooo old

**Pull request closed without merging**
